class Genres():

    def getNumGenre(self, genre):
        switcher = {
            "Blues":                  0,
            "Classic Rock":           1,
            "Country":                2,
            "Dance":                  3,
            "Disco":                  4,
            "Funk":                   5,
            "Grunge":                 6,
            "Hip-Hop":                7,
            "Jazz":                   8,
            "Metal":                  9,
            "New Age":                10,
            "Oldies":                 11,
            "Other":                  12,
            "Pop":                    13,
            "R&B":                    14,
            "Rap":                    15,
            "Reggae":                 16,
            "Rock":                   17,
            "Techno":                 18,
            "Industrial":             19,
            "Alternative":            20,
            "Ska":                    21,
            "Death Metal":            22,
            "Pranks":                 23,
            "Soundtrack":             24,
            "Euro-Techno":            25,
            "Ambient":                26,
            "Trip-Hop":               27,
            "Vocal":                  28,
            "Jazz+funk":              29,
            "Fusion":                 30,
            "Trance":                 31,
            "Classical":              32,
            "Instrumental":           33,
            "Acid":                   34,
            "House":                  35,
            "Game":                   36,
            "Sound Clip":             37,
            "Gospel":                 38,
            "Noise":                  39,
            "Alternrock":             40,
            "Bass":                   41,
            "Soul":                   42,
            "Punk":                   43,
            "Space":                  44,
            "Meditative":             45,
            "Instrumental Pop":       46,
            "Instrumental Rock":      47,
            "Ethnic":                 48,
            "Gothic":                 49,
            "Darkwave":               50,
            "Techno-Industrial":      51,
            "Electronic":             52,
            "Pop-Folk":               53,
            "Eurodance":              54,
            "Dream":                  55,
            "Southern Rock":          56,
            "Comedy":                 57,
            "Cult":                   58,
            "Gangsta":                59,
            "Top 40":                 60,
            "Christian Rap":          61,
            "Pop/Funk":               62,
            "Jungle":                 63,
            "Native American":        64,
            "Cabaret":                65,
            "New Wave":               66,
            "Psychadelic":            67,
            "Rave":                   68,
            "Showtunes":              69,
            "Trailer":                70,
            "Lo-Fi":                  71,
            "Tribal":                 72,
            "Acid Punk":              73,
            "Acid Jazz":              74,
            "Polka":                  75,
            "Retro":                  76,
            "Musical":                77,
            "Rock & Roll":            78,
            "Hard Rock":              79,
            "Folk":                   80,
            "Folk-Rock":              81,
            "National Folk":          82,
            "Swing":                  83,
            "Fast Fusion":            84,
            "Bebob":                  85,
            "Latin":                  86,
            "Revival":                87,
            "Celtic":                 88,
            "Bluegrass":              89,
            "Avantgarde":             90,
            "Gothic Rock":            91,
            "Progressive Rock":       92,
            "Psychedelic Rock":       93,
            "Symphonic Rock":         94,
            "Slow Rock":              95,
            "Big Band":               96,
            "Chorus":                 97,
            "Easy Listening":         98,
            "Acoustic":               99,
            "Humour":                 100,
            "Speech":                 101,
            "Chanson":                102,
            "Opera":                  103,
            "Chamber Music":          104,
            "Sonata":                 105,
            "Symphony":               106,
            "Booty Bass":             107,
            "Primus":                 108,
            "Porn Groove":            109,
            "Satire":                 110,
            "Slow Jam":               111,
            "Club":                   112,
            "Tango":                  113,
            "Samba":                  114,
            "Folklore":               115,
            "Ballad":                 116,
            "Power Ballad":           117,
            "Rhythmic Soul":          118,
            "Freestyle":              119,
            "Duet":                   120,
            "Punk Rock":              121,
            "Drum Solo":              122,
            "A Capella":              123,
            "Euro-House":             124,
            "Dance Hall":             125,
            "Goa":                    126,
            "Drum & Bass":            127,
            "Club-House":             128,
            "Hardcore":               129,
            "Terror":                 130,
            "Indie":                  131,
            "Britpop":                132,
            "Negerpunk":              133,
            "Polsk Punk":             134,
            "Beat":                   135,
            "Christian Gangsta Rap":  136,
            "Heavy Metal":            137,
            "Black Metal":            138,
            "Crossover":              139,
            "Contemporary Christian": 140,
            "Christian Rock":         141,
            "Merengue":               142,
            "Salsa":                  143,
            "Trash Metal":            144,
            "Anime":                  145,
            "Jpop":                   146,
            "Synthpop":               147,
            "Abstract":               148,
            "Art Rock":               149,
            "Baroque":                150,
            "Bhangra":                151,
            "Big Beat":               152,
            "Breakbeat":              153,
            "Chillout":               154,
            "Downtempo":              155,
            "Dub":                    156,
            "Ebm":                    157,
            "Eclectic":               158,
            "Electro":                159,
            "Electroclash":           160,
            "Emo":                    161,
            "Experimental":           162,
            "Garage":                 163,
            "Global":                 164,
            "Idm":                    165,
            "Illbient":               166,
            "Industro-Goth":          167,
            "Jam Band":               168,
            "Krautrock":              169,
            "Leftfield":              170,
            "Lounge":                 171,
            "Math Rock":              172,
            "New Romantic":           173,
            "Nu-Breakz":              174,
            "Post-Punk":              175,
            "Post-Rock":              176,
            "Psytrance":              177,
            "Shoegaze":               178,
            "Space Rock":             179,
            "Trop Rock":              180,
            "World Music":            181,
            "Neoclassical":           182,
            "Audiobook":              183,
            "Audio Theatre":          184,
            "Neue Deutsche Welle":    185,
            "Podcast":                186,
            "Indie Rock":             187,
            "G-Funk":                 188,
            "Dubstep":                189,
            "Garage Rock":            190,
            "Psybient":               191
        }
        return switcher.get(genre, "Invalid genre")

    def getStringGenre(self, numGenre):
        switcher = {
            1:   "Blues",
            2:   "Classic Rock",
            3:   "Country",
            4:   "Disco",
            5:   "Funk",
            6:   "Grunge",
            7:   "Hip-Hop",
            8:   "Jazz",
            9:   "Metal",
            10:  "New Age",
            11:  "Oldies",
            12:  "Other",
            13:  "Pop",
            14:  "R&B",
            15:  "Rap",
            16:  "Reggae",
            17:  "Rock",
            18:  "Techno",
            19:  "Industrial",
            20:  "Alternative",
            21:  "Ska",
            22:  "Death Metal",
            23:  "Pranks",
            24:  "Soundtrack",
            25:  "Euro-Techno",
            26:  "Ambient",
            27:  "Trip-Hop",
            28:  "Vocal",
            29:  "Jazz+funk",
            30:  "Fusion",
            31:  "Trance",
            32:  "Classical",
            33:  "Instrumental",
            34:  "Acid",
            35:  "House",
            36:  "Game",
            37:  "Sound Clip",
            38:  "Gospel",
            39:  "Noise",
            40:  "Alternrock",
            41:  "Bass",
            42:  "Soul",
            43:  "Punk",
            44:  "Space",
            45:  "Meditative",
            46:  "Instrumental Pop",
            47:  "Instrumental Rock",
            48:  "Ethnic",
            49:  "Gothic",
            50:  "Darkwave",
            51:  "Techno-Industrial",
            52:  "Electronic",
            53:  "Pop-Folk",
            54:  "Eurodance",
            55:  "Dream",
            56:  "Southern Rock",
            57:  "Comedy",
            58:  "Cult",
            59:  "Gangsta",
            60:  "Top 40",
            61:  "Christian Rap",
            62:  "Pop/Funk",
            63:  "Jungle",
            64:  "Native American",
            65:  "Cabaret",
            66:  "New Wave",
            67:  "Psychadelic",
            68:  "Rave",
            69:  "Showtunes",
            70:  "Trailer",
            71:  "Lo-Fi",
            72:  "Tribal",
            73:  "Acid Punk",
            74:  "Acid Jazz",
            75:  "Polka",
            76:  "Retro",
            77:  "Musical",
            78:  "Rock & Roll",
            79:  "Hard Rock",
            80:  "Folk",
            81:  "Folk-Rock",
            82:  "National Folk",
            83:  "Swing",
            84:  "Fast Fusion",
            85:  "Bebob",
            86:  "Latin",
            87:  "Revival",
            88:  "Celtic",
            89:  "Bluegrass",
            90:  "Avantgarde",
            91:  "Gothic Rock",
            92:  "Progressive Rock",
            93:  "Psychedelic Rock",
            94:  "Symphonic Rock",
            95:  "Slow Rock",
            96:  "Big Band",
            97:  "Chorus",
            98:  "Easy Listening",
            99:  "Acoustic",
            100: "Humour",
            101: "Speech",
            102: "Chanson",
            103: "Opera",
            104: "Chamber Music",
            105: "Sonata",
            106: "Symphony",
            107: "Booty Bass",
            108: "Primus",
            109: "Porn Groove",
            110: "Satire",
            111: "Slow Jam",
            112: "Club",
            113: "Tango",
            114: "Samba",
            115: "Folklore",
            116: "Ballad",
            117: "Power Ballad",
            118: "Rhythmic Soul",
            119: "Freestyle",
            120: "Duet",
            121: "Punk Rock",
            122: "Drum Solo",
            123: "A Capella",
            124: "Euro-House",
            125: "Dance Hall",
            126: "Goa",
            127: "Drum & Bass",
            128: "Club-House",
            129: "Hardcore",
            130: "Terror",
            131: "Indie",
            132: "Britpop",
            133: "Negerpunk",
            134: "Polsk Punk",
            135: "Beat",
            136: "Christian Gangsta Rap",
            137: "Heavy Metal",
            138: "Black Metal",
            139: "Crossover",
            140: "Contemporary Christian",
            141: "Christian Rock",
            142: "Merengue",
            143: "Salsa",
            144: "Trah Metal",
            145: "Anime",
            146: "Jpop",
            147: "Synthpop",
            148: "Abstract",
            149: "Art Rock",
            150: "Baroque",
            151: "Bhangra",
            152: "Big Beat",
            153: "Breakbeat",
            154: "Chillout",
            155: "Downtempo",
            156: "Dub",
            157: "Ebm",
            158: "Eclectic",
            159: "Electro",
            160: "Electroclash",
            161: "Emo",
            162: "Experimental",
            163: "Garage",
            164: "Global",
            165: "Idm",
            166: "Illbient",
            167: "Industro-Goth",
            168: "Jam Band",
            169: "Krautrock",
            170: "Leftfield",
            171: "Lounge",
            172: "Math Rock",
            173: "New Romantic",
            174: "Nu-Breakz",
            175: "Post-Punk",
            176: "Post-Rock",
            177: "Psytrance",
            178: "Shoegaze",
            179: "Space Rock",
            180: "Trop Rock",
            181: "World Music",
            182: "Neoclassical",
            183: "Audiobook",
            184: "Audio Theatre",
            185: "Neue Deutsche Welle",
            186: "Podcast",
            187: "Indie Rock",
            188: "G-Funk",
            189: "Dubstep",
            190: "Garage Rock",
            191: "Psybient"
        }
        return switcher.get(numGenre, "Invalid genre number ")
